### ISSUE TITLE
Nuevo Issue de Ejemplo

### ISSUE THREAD

**Issue by brian101016** [chainbreaker11/git-act-final#7]
Acabo de revisar su repositorio, y está excelentemente.

Este mensaje es de confirmación de que su equipo (2 personas) acreditaron el taller de GIT, enhorabuena :)

Puedo observar que trabajaron con ramas según la funcionalidad de la calculadora, que era un aspecto que nos comentaba Arturo que ellos realizan en ENCORA. Veo que ustedes ya tienen experiencia utilizando GitHub, y este repositorio es claro ejemplo de ello. A pesar de esto, espero que hayan podido aprender algo nuevo y los animo a seguir experimentando con esta herramienta muy importante.

Nuevamente, muchas gracias por haber participado en el taller 👍 

PD: Ya los marqué con 100%, y también les marqué la #6  ( se quedó pendiente! )
(Cuando lean este mensaje, marquen el Issue como completado)

**Comment by luisillo77D** [comment]
muben
